In [ ]:
# 3 parts;   1: data preprocessing  2: Building NN  3: Prediction & Evaluation

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
cust_df = pd.read_csv('d:/datasets/analytics/Churn_Modelling.csv')

In [3]:
cust_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# DATA PREPROCESSING STEP

In [5]:
X = cust_df.iloc[:,3:13].values

In [6]:
y = cust_df.iloc[:,13].values

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [9]:
labelencoder_X_1 = LabelEncoder()

In [10]:
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])

In [11]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [12]:
labelencoder_x_2 = LabelEncoder()

In [13]:
X[:,2] = labelencoder_x_2.fit_transform(X[:,2])

In [14]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
# for geography
onehotencoder = OneHotEncoder(categorical_features=[1])

In [16]:
X  = onehotencoder.fit_transform(X).toarray()

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [17]:
X.shape

(10000, 12)

In [18]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [19]:
X = X[:,1:]

In [20]:
X.shape

(10000, 11)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test, y_train,y_test  = train_test_split(X,y, test_size=0.25)

In [23]:
# Features Scaling -- required for deep learning

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)


In [38]:
# BUILD ANN

import keras

In [39]:
from keras.models import Sequential
from keras.layers import Dense


In [40]:
# initialize the NN

customer_classifier = Sequential()

In [41]:
# Adding the first input later and hidden layer
customer_classifier.add(Dense(output_dim = 6, init = 'uniform',activation='relu',input_dim=11))

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [42]:
# Second Hidden Layer
customer_classifier.add(Dense(output_dim = 6, init = 'uniform',activation='relu'))

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [43]:
# Third Hidden Layer
customer_classifier.add(Dense(output_dim = 6, init = 'uniform',activation='relu'))

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [44]:
customer_classifier.add(Dense(output_dim = 1, init = 'uniform',activation='sigmoid'))

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [45]:
# Compile the
customer_classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [46]:
customer_classifier.fit(X_train,y_train,batch_size=10,nb_epoch = 300)

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/300
7500/7500 [==============================] - 3s 346us/step - loss: 0.4832 - accuracy: 0.7968
Epoch 2/300
7500/7500 [==============================] - 1s 145us/step - loss: 0.4192 - accuracy: 0.7968
Epoch 3/300
7500/7500 [==============================] - 1s 157us/step - loss: 0.4079 - accuracy: 0.8172
Epoch 4/300
7500/7500 [==============================] - 1s 139us/step - loss: 0.3968 - accuracy: 0.8301
Epoch 5/300
7500/7500 [==============================] - 1s 138us/step - loss: 0.3878 - accuracy: 0.8307
Epoch 6/300
7500/7500 [==============================] - 1s 142us/step - loss: 0.3796 - accuracy: 0.8432
Epoch 7/300
7500/7500 [==============================] - 1s 165us/step - loss: 0.3749 - accuracy: 0.8475
Epoch 8/300
7500/7500 [==============================] - 1s 140us/step - loss: 0.3707 - accuracy: 0.8496
Epoch 9/300
7500/7500 [==============================] - 1s 165us/step - loss: 0.3680 - accuracy: 0.8491
Epoch 10/300
7500/7500 [==============================]

In [ ]:
#loss: 0.3922 - accuracy: 0.8407

# 200 Epochs
loss: 0.3372 - accuracy: 0.8605
# 300 Epochs
loss: 0.3350 - accuracy: 0.8632
        
# with Three Hidden Layers
loss: 0.3348 - accuracy: 0.8627

In [65]:
predictions = customer_classifier.predict(X_test)    

In [66]:
predictions

array([[0.08663528],
       [0.12744227],
       [0.12569599],
       ...,
       [0.65391386],
       [0.27728027],
       [0.23271425]], dtype=float32)

In [68]:
predictions [predictions > 0.50] 

array([0.7145028 , 0.6362007 , 0.6114517 , 0.8487217 , 0.83487576,
       0.77793986, 0.5255283 , 0.5922449 , 0.87367415, 0.6087518 ,
       0.6786688 , 0.5571901 , 0.655976  , 0.87917465, 0.87108403,
       0.606563  , 0.81445515, 0.8381801 , 0.54354393, 0.8543929 ,
       0.5432707 , 0.6567862 , 0.7872584 , 0.50369185, 0.6078167 ,
       0.6229349 , 0.80078214, 0.6864048 , 0.5446605 , 0.5635291 ,
       0.53279704, 0.7240267 , 0.5098967 , 0.51907355, 0.713593  ,
       0.5577543 , 0.6085036 , 0.61685413, 0.52298415, 0.5145653 ,
       0.82159126, 0.82154155, 0.55197316, 0.76056933, 0.86127055,
       0.87917465, 0.5114295 , 0.7462549 , 0.5685871 , 0.5854186 ,
       0.8415954 , 0.5337203 , 0.5421252 , 0.6505044 , 0.57700986,
       0.5051142 , 0.80209446, 0.85751975, 0.6562799 , 0.87917465,
       0.87369955, 0.7012896 , 0.8105486 , 0.56179315, 0.8625898 ,
       0.8433575 , 0.7456593 , 0.7940487 , 0.5830245 , 0.87917465,
       0.868696  , 0.76432   , 0.8771994 , 0.8661692 , 0.79327

In [69]:
customer_classifier.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [36]:
customer_classifier.save('d:/models/Customer_Churn_Model.h5')

In [ ]:
from keras.models import load_model
Customer_churn = load_model('d:/Models/Customer_Churn_Model.h5')
# Customer_churn.predict()